sonar.projectKey=IreneCitas
sonar.projectName=IreneCitas
sonar.host.url=http://localhost:9000

sonar.sources=app,bootstrap,config,database,lang,public,resources,routes
sonar.tests=tests

sonar.exclusions=**/node_modules/**,**/vendor/**,**/storage/**,**/bootstrap/cache/**,**/.phpunit.cache/**,**/build/**

sonar.test.exclusions=**/node_modules/**,**/vendor/**

sonar.sourceEncoding=UTF-8